<h3>Welcome</h3>
<p>Checkout here why Pike_Grid is so awesome! For the moment Pike_Grid only 
    can work with Doctrine2 as data provider but we hope some people will adapt
    the Zend ORM, Propal layers too.</p>

<h3>Installation</h3>
<p>This example application uses a SQLlite database. SQLLite can work with a file
    and doesn't need server specific configuration. When you have a package manager on your
    linux ditribution you proberly need to install the package "php5-sqlite3"</p>

<h3>Reference</h3>
<p>You can check out the latest Pike source from <a href="http://code.google.com/p/php-pike/source/checkout" target="_blank">subversion</a> or our zipped packages. Pike_Grid
    is available from the Pike0.3 package. At the Pike wiki you can read more about the features in the Pike package. </p>
<p>After the documentation of Pike you should take a look at 
    <a href="http://framework.zend.com/docs/overview" target="_blank">Zend Framework</a> documentation and 
    <a href="http://www.trirand.com/jqgridwiki/doku.php" target="_blank">jqGrid</a> documentation. 
    Also it's important you have acknowledge of using <a href="http://jquery.com/" target="_blank">jQuery</a>
    and <a href="http://www.doctrine-project.org/projects/orm/2.1/docs/en" target="_blank">Doctrine</a>.</p>
