<?php echo $this->doctype('XHTML1_TRANSITIONAL') ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head> 
        <?php echo $this->headTitle() ?>	
        <?php echo $this->headStyle() ?>
        <?php echo $this->headLink() ?> 
        <?php echo $this->headMeta() ?> 
    </head>

    <body>
        <?php if (Zend_Auth::getInstance()->hasIdentity()) : ?>
            <div id="userContainer">
                <div class="user-info">
                    Welcome back, <?php echo Zend_Auth::getInstance()->getIdentity()->username ?> 
                    <a class="button" href="<?php echo $this->url(array('controller' => 'user', 'action' => 'logout'), 'default') ?>">
                        Logout
                    </a>
                </div>
            </div>
        <?php else : ?>
            <div id="loginContainer"><?php echo $this->loginForm->render() ?></div>
        <?php endif; ?>
        <div id="mainContainer">             
            <div id="sidebar-left">
                <div id="header">
                    <a href="/" title="PiKe"><img src="<?php echo $this->baseUrl() ?>/images/logo.png" /></a>
                </div>
                <?php echo $this->navigation()->menu()->render(); ?>
                <div id="promo">
                    <a href="http://wiki.pike-project.org" title="Wiki"><img src="<?php echo $this->baseUrl() ?>/images/wiki-logo.png" /></a>
                    <br /><br />
                    <a href="http://github.com/php-pike" title="Follow PiKe on Github!" target="_blank"><img src="<?php echo $this->baseUrl() ?>/images/github-logo.png" /></a>
                </div>
            </div>
            <div class="content">                
                <?= $this->flashMessages() ?>                                
                <?php echo $this->layout()->content ?>
            </div>
        </div>
        <?php echo $this->headScript() ?>
    </body>
</html>
