<?php echo $this->doctype('XHTML1_TRANSITIONAL') ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head> 
        <?php echo $this->headTitle() ?>	
        <?php echo $this->headStyle() ?>
        <?php echo $this->headLink() ?> 
        <?php echo $this->headMeta() ?> 
    </head>

    <body>
        <div id="loginContainer">
            <?php echo $this->loginForm->render() ?>
        </div>
        <div id="mainContainer">             
            <div id="sidebar-left">
                <div id="header">
                    <a href="/" title="PiKe"><img src="<?php echo $this->baseUrl() ?>/images/logo.png" /></a>
                </div>
                <?php echo $this->navigation()->menu()->render(); ?>
                <div id="promo">
                    <a href="http://wiki.pike-project.org" title="Wiki"><img src="<?php echo $this->baseUrl() ?>/images/wiki-logo.png" /></a>
                    <br /><br />
                    <a href="http://github.com/php-pike" title="Follow PiKe on Github!" target="_blank"><img src="<?php echo $this->baseUrl() ?>/images/github-logo.png" /></a>
                </div>
            </div>
            <div class="content">
                <h1>The power of Pike_Grid!</h1>
                <p class="intro">Look at these great examples which convince you about the simplicity of Pike_Grid. It's also a good
                    piece of advise to take a good look at the 
                    <a href="http://framework.zend.com/docs/overview" title="Zend Framework documentation" target="_blank">Zend Framework documentation</a>
                    and <a href="http://www.trirand.com/jqgridwiki/doku.php" target="_blank" title="jqGrid documentation">jqGrid documentation</a>.</p>                 

                <?php echo $this->layout()->content ?>
            </div>
        </div>
        <?php echo $this->headScript() ?>
    </body>
</html>
